### ISSUE TITLE
bug: description field's background is wrong

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/design-system#102]
## Context

The description field's background should not be white

![截圖 2023-02-10 下午5 34 08](https://user-images.githubusercontent.com/57251712/218056431-7a522083-01f9-4d10-813d-b5fbc38b629a.png)

**Comment by Dinokojt7** [comment]
Hi what color should it be?

**Comment by EiffelFly** [comment]
@Dinokojt7 It should be transparent! But I am sorry that I need to fix this issue by myself due to we are rushing a release today. It is still our pleasure that you are contributing into this project. If you want to contribute to our projects, your could look into our product-website's issues. They are more stable and we can get more time to make it through!
