### ISSUE TITLE
refactor: add tsconfig for absolute path

### ISSUE THREAD

**Issue by iamnamananand996** [instill-ai/design-system#332]
```
import { Nullable } from "../../../types/general";
import { CheckIcon } from "../../Icons";
```

it can be written in better way

```
import { Nullable } from "@types/general";
import { CheckIcon } from "@ui/Icons";

or

import { Nullable } from "types/general";
import { CheckIcon } from "ui/Icons";

or

import { Nullable } from "@cortex-types/general";
import { CheckIcon } from "@cortex-ui/Icons";
```

adding relative path can become difficult to read, when it more the 2 or 3 steps.

we should add some configs for these
ref : https://www.typescriptlang.org/tsconfig#paths

cc - @EiffelFly

**Comment by EiffelFly** [comment]
@iamnamananand996 I deliberately avoid this pattern in this repo to make sure everything works without the help of tsconfig. In this way we can reduce the possibility of bumping into some module import/export issue when bundle the package

**Comment by iamnamananand996** [comment]
closed this issue because of the above comment.
